# api redirect.
[[redirects]]
  from = "/api/*"
  to = "https://poring.world/:splat"
  status = 200
  force = true

# SPA router support.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200