# api redirect.
[[redirects]]
  from = "https://rofinder.netlify.app/api/*"
  to = "https://poring.world/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


# api redirect.
[[redirects]]
  from = "/api/*"
  to = "https://poring.world/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# SPA router support.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200